### ISSUE TITLE
Amiibo Keys

### ISSUE THREAD

**Issue by Muchieman** [AcK77/AmiiBomb-uino#5]
I got some amiibo keys (.bin files) and when I try to put them into amiibomb I get Wrong Amiibo Keys File! Would you select again? I have no idea why this is happening and I can't get a different result.

**Comment by urherenow** [comment]
Github is not a support forum. This space is for issues/enhancements in the code.

There aren't key "files". There is only 1 key file. I know what your problem is, but I'm unable to tell you without sounding like a jerk...

**Comment by Muchieman** [comment]
ok I got the "key file" and it still says that. I'm not on here for support i'm telling you it doesn't work

**Comment by urherenow** [comment]
It does work. Post on gbatemp and you may get the help you need.

**Comment by AcK77** [comment]
@urherenow:
This Space it's for any kind of problems with AmiiBomb, a problem will be come to an issues in the code so there is no problems with that ;)!

@Muchieman:
But instead of what I said at the way up, you have a wrong Keys file. As I explain you on GBATemp, follow the instructions of AmiiBomb when you don't have any Keys file and all will be good. 
Anyone can send you Keys file if that what you want. It's not allowed to provide them due to the copyright.
